version: "2.1"

services:
  ############
  # HEIMDALL #
  ############
  heimdall:
    image: linuxserver/heimdall
    container_name: htpc-heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/heimdall:/config
    ports:
      - ${HEIMDALL_PORT}:80
      - ${HEIMDALL_PORT_SSH}:443
    expose:
      - ${HEIMDALL_PORT}
      - ${HEIMDALL_PORT_SSH}
    restart: ${RESTART_POLICY}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'


  ##########
  # SONARR #
  ##########
  sonarr:
    image: linuxserver/sonarr
    container_name: htpc-sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${CONFIG_PATH}/sonarr-rtc:/dev/rtc:ro
      - ${SERIES_PATH}:/tv
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - ${SONARR_PORT}:8989
    expose:
      - ${SONARR_PORT}
    restart: ${RESTART_POLICY}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'


  ##########
  # RADARR #
  ##########
  radarr:
    image: linuxserver/radarr
    container_name: htpc-radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MOVIES_PATH}:/movies
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - ${RADARR_PORT}:7878
    expose:
      - ${RADARR_PORT}
    restart: ${RESTART_POLICY}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'


  ###########
  # JACKETT #
  ###########
  jackett:
    image: linuxserver/jackett
    container_name: htpc-jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - AUTO_UPDATE=true
    volumes:
      - ${CONFIG_PATH}/jackett:/config
      - ${BLACKHOLE_PATH}:/downloads
    ports:
      - ${JACKETT_PORT}:9117
    expose:
      - ${JACKETT_PORT}
    restart: ${RESTART_POLICY}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'


  ################
  # TRANSMISSION #
  ################
  transmission:
    image: linuxserver/transmission
    container_name: htpc-transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - ${CONFIG_PATH}/transmission:/config
      - ${DOWNLOAD_PATH}:/downloads
      - ${BLACKHOLE_PATH}:/watch
    ports:
      - ${TRANSMISSION_PORT}:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - ${TRANSMISSION_PORT}
      - 51413
      - 51413/udp
    restart: ${RESTART_POLICY}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'


  ##########
  # BAZARR #
  ##########
  bazarr:
    image: linuxserver/bazarr
    container_name: htpc-bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${SERIES_PATH}:/tv
      - ${MOVIES_PATH}:/movies
    ports:
      - ${BAZARR_PORT}:6767
    expose:
      - ${BAZARR_PORT}
    restart: ${RESTART_POLICY}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'


  ############
  # JELLYFIN #
  ############
  jellyfin:
    image: linuxserver/jellyfin
    container_name: htpc-jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config
      - ${SERIES_PATH}:/data/tvshows
      - ${MOVIES_PATH}:/data/movies
      - ${YOUTUBE_PATH}:/data/youtube
    ports:
      - ${JELLYFIN_PORT}:8096
      - ${JELLYFIN_PORT_SSH}:8090
    expose:
      - ${JELLYFIN_PORT}
      - ${JELLYFIN_PORT_SSH}
    devices:
      - /dev/dri:/dev/dri
    restart: ${RESTART_POLICY}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'


  ########
  # OMBI #
  ########
  ombi:
    image: linuxserver/ombi
    container_name: htpc-ombi
    # hostname: ombi
    # domainname: ombi.htpc
    # mac_address: 00:00:00:41:16:01
    # networks:
    #   - htpc-public
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - BASE_URL=/ombi
    volumes:
      - ${CONFIG_PATH}/ombi:/config
    ports:
      - ${OMBI_PORT}:3579
    expose:
      - ${OMBI_PORT}
    restart: ${RESTART_POLICY}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'


  ##############
  # YOUTUBE-DL #
  ##############
  youtube:
    image: kmb32123/youtube-dl-server
    container_name: youtube-dl
    volumes:
      - ${YOUTUBE_PATH}:/youtube-dl
    ports:
      - ${YOUTUBE_PORT}:8080
    expose:
      - ${YOUTUBE_PORT}
    restart: ${RESTART_POLICY}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'


  ###########
  # READARR #
  ###########
  readarr:
    container_name: readarr
    image: hotio/readarr:nightly
    restart: ${RESTART_POLICY}
    ports:
      - "${READARR_PORT}:8787"
    expose:
      - ${READARR_PORT}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
      - ARGS
    volumes:
      - ${CONFIG_PATH}/readarr:/config
      - ${BOOKS_PATH}:/books
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'


  #############
  # PORTAINER #
  #############
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - ${DOCKER_SOCKET}:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - ${PORTAINER_PORT_UI}:9000
      - ${PORTAINER_PORT_SSH}:8000
    expose:
      - ${PORTAINER_PORT_UI}
      - ${PORTAINER_PORT_SSH}
    restart: ${RESTART_POLICY}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'


  # ==============
  # = WATCHTOWER =
  # ==============
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: ${RESTART_POLICY}
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=${WATCHTOWER_LABEL_UPDATE}
      - 'WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}'
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATION}
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${WATCHTOWER_SLACK}
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=Watchtower
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${SMTP_FROM}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_SERVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASS}
    volumes:
      - ${DOCKER_SOCKET}:/var/run/docker.sock
      - /etc/ssl/certs:/etc/ssl/certs
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
      # - 'traefik.enable=false'


  # Evaluation section :)

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    privileged: true
    network_mode: host
    # networks:
    #   - socket_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "61208:61208"
    pid: host
    volumes:
      # - $DOCKERDIR/glances/glances.conf:/glances/conf/glances.conf # Use this if you want to add a glances.conf file
      - /var/run/docker.sock:/var/run/docker.sock:ro # Use Docker Socket Proxy instead for improved security
    # environment:
    #   # GLANCES_OPT: "-C /glances/conf/glances.conf --quiet --export influxdb"
    #   GLANCES_OPT: "-w"
    #   DOCKER_HOST: tcp://socket-proxy:2375

  # calibre-web:
  #   image: ghcr.io/linuxserver/calibre-web
  #   container_name: calibre-web
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - DOCKER_MODS=linuxserver/calibre-web:calibre
  #   volumes:
  #     - /volume1/Personal/sync/dropbox/htpc/docker-compose/test/calibre-web:/config
  #     # - /volume1/Media/Books:/books
  #   ports:
  #     - 8083:8083
  #   restart: unless-stopped

  # too simple for my needs
  # photoshow:
  #   image: ghcr.io/linuxserver/photoshow
  #   container_name: photoshow
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - /volume1/Personal/sync/dropbox/htpc/docker-compose/test/photoshow:/config
  #     - /volume1/Personal/sync/dropbox/htpc/docker-compose/test/photoshow-pics:/Pictures:ro
  #     - /volume1/Personal/sync/dropbox/htpc/docker-compose/test/photoshow-thumbs:/Thumbs
  #   ports:
  #     - 8027:80
  #   restart: unless-stopped


  # for plex :(
  # overseerr:
  #   container_name: overseerr
  #   image: hotio/overseerr
  #   ports:
  #     - "5055:5055"
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - UMASK=002
  #     - TZ=${TZ}
  #     - ARGS
  #   volumes:
  #     - /volume1/Personal/sync/dropbox/htpc/docker-compose/test/overseerr:/config

volumes:
  portainer_data:
