docker save -o images\heimdall.tar linuxserver/heimdall
docker save -o images\sonarr.tar linuxserver/sonarr
docker save -o images\radarr.tar linuxserver/radarr
docker save -o images\prowlarr.tar lscr.io/linuxserver/prowlarr:develop
docker save -o images\transmission.tar linuxserver/transmission
docker save -o images\bazarr.tar linuxserver/bazarr
docker save -o images\jellyfin.tar linuxserver/jellyfin
docker save -o images\ombi.tar linuxserver/ombi
docker save -o images\youtube-dl-server.tar kmb32123/youtube-dl-server
docker save -o images\readarr.tar hotio/readarr:nightly
docker save -o images\watchtower.tar containrrr/watchtower
