version: "3"

services:
  ################
  # TRANSMISSION #
  ################
  transmission:
    image: haugene/transmission-openvpn
    container_name: htpc-transmission
    cap_add:
        - NET_ADMIN
    volumes:
        - ${DATA_PATH}:/data
        # - ${DOWNLOAD_PATH}:/downloads
        - ${BLACKHOLE_PATH}:/watch
        - ${CONFIG_PATH}/transmission-vpn:/config
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - TRANSMISSION_WEB_UI=transmission-web-control
        - OPENVPN_PROVIDER=NORDVPN
        - OPENVPN_CONFIG=france
        - OPENVPN_USERNAME=
        - OPENVPN_PASSWORD=
        # - NORDVPN_CATEGORY=
        # https://api.nordvpn.com/v1/servers/countries
        # - NORDVPN_COUNTRY=US
        - NORDVPN_PROTOCOL=tcp
        - LOCAL_NETWORK=192.168.0.0/24
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - ${TRANSMISSION_PORT}:9091
    restart: ${RESTART_POLICY}
