docker load -i heimdall.tar
docker load -i sonarr.tar
docker load -i radarr.tar
docker load -i prowlarr.tar
docker load -i transmission.tar
docker load -i bazarr.tar
docker load -i jellyfin.tar
docker load -i ombi.tar
docker load -i youtube-dl
docker load -i readarr.tar
docker load -i portainer-ce
docker load -i watchtower.tar
docker load -i duplicati.tar
